from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT

def generate_prescription_pdf(data: dict) -> BytesIO:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=24,
        alignment=TA_CENTER,
        spaceAfter=20,
        textColor=colors.teal
    )
    
    header_style = ParagraphStyle(
        'Header',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.gray
    )

    # 1. Header
    elements.append(Paragraph("Medical Prescription Report", title_style))
    elements.append(Paragraph("Generated by AI Prescription Assistant", header_style))
    elements.append(Spacer(1, 20))

    # 2. Patient Info
    # Check if data structure is nested in 'structured_prescription' or flat
    # We assume the API passes the full analysis object
    
    # We might need to handle cases where data is missing
    evaluation = data.get('evaluation', {})
    score = data.get('score', 'N/A')
    
    # Assuming the frontend passes the original input data (patient info) along with the analysis
    # For now, let's look at the structured prescription
    medicines = data.get('structured_prescription', [])

    # Score Section
    elements.append(Paragraph(f"Safety Score: {score}/100", styles['Heading2']))
    elements.append(Paragraph(f"Rating: {evaluation.get('overall_rating', 'N/A')}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # 3. Prescription Table
    elements.append(Paragraph("Prescribed Medicines", styles['Heading2']))
    elements.append(Spacer(1, 10))

    if medicines:
        table_data = [['Medicine', 'Dosage', 'Frequency', 'Duration', 'Notes/Warnings']]
        
        for med in medicines:
            # Format warnings
            warnings = ", ".join(med.get('warnings', []))
            
            row = [
                med.get('medicine_name', 'Unknown'),
                med.get('strength', '-'),
                med.get('frequency', '-'),
                med.get('duration', '-'),
                warnings if warnings else med.get('timing', '-')
            ]
            table_data.append(row)

        table = Table(table_data, colWidths=[120, 80, 100, 80, 150])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.teal),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph("No medicines found in the analysis.", styles['Normal']))

    # 4. Disclaimer
    elements.append(Spacer(1, 40))
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)
    elements.append(Paragraph("Disclaimer: This report is generated by AI assistant and should be verified by a certified medical professional.", disclaimer_style))

    doc.build(elements)
    buffer.seek(0)
    print(buffer)
    return buffer
